name: vattenfalldynamicpriceapi
services:
  vattenfalldynamicpriceapi:
    container_name: vattenfalldynamicpriceapi
    image: vattenfalldynamicpriceapi
    build:
      context: .
      dockerfile: VattenfallDynamicPriceApi/Dockerfile
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Amsterdam
      - ASPNETCORE_URLS=http://+:8080
      # You should be able to leave these commented, but if something changes in production, this could be a quick fix
      #- VFAPI_UseKnownValues=false
      #- VFAPI_ScrapePageUrl=
      #- VFAPI_KnownApiBaseUrl=
      #- VFAPI_KnownApiKey=
